### ISSUE TITLE
load-config doesn't work with only :merge (or no key)

### ISSUE THREAD

**Issue by lerouxrgd** [tolitius/cprop#11]
Simply reproduce with:

```
$ lein try cprop
=> (use 'cprop.core)
=> (load-config :merge [{:foo "bar"}])
RuntimeException could not find a configuration file to load. looked in the classpath (as a "resource") and on a file system via "conf" system property  cprop.core/load-config (core.clj:24)
```

I guess this is due to `ignore-missing-default` returning an empty map when no `:file` or `:resource` are provided.
However the doc has examples like `(load-config :merge [...])`.
Moreover it is also stated that simply `(load-config)` should work.

**Comment by tolitius** [comment]
By default `cprop` would look in two places for configuration files:

* classpath: for the `config.edn` resource
* file system: for a path identified by the `conf` system property

If both are there, they will be merged. A `file system` source would override matching properties from a `classpath` source,
and the result will be [merged with System properties](README.md#merging-with-system-properties)
and then [merged with ENV variables](README.md#merging-with-env-variables)
for all the _matching_ properties.

check out [cprop test](test/cprop/test/core.clj) to see `(load-config)` in action.

---

so the idea is that if relies on the configuration file (i.e. `config.edn`, or another, non default name) _to be "there"_. All the merges happen _to_ this file.

For example this would work:

```
$ lein try cprop

user=> (use 'cprop.core)
user=> (spit "i-need-to-exist.edn" "{:a 42}")
user=> (load-config :file "i-need-to-exist.edn")
{:a 42}
```

Are you looking for a different behavior?

**Comment by lerouxrgd** [comment]
Ok I see, when I read it the first time I didn't think that at least one of `:file` or `config.edn` on classpath was mandatory.
I think that as a default behavior explicit (empty map) is better than implicit (expecting a file called `config.edn` somewhere on the classpath).
But it is a matter of taste that is up to you desinging the lib, so don't hesitate to close the issue, thanks.

**Comment by tolitius** [comment]
Currently, in case it does not find a `resource` or a `file` cprop would complain. This complaint is quite welcome beyond development, since it communicates the fact that the file that was given via `ENV` or `-D` or a classpath was not found: i.e. _it is clear_, and does not start an application _without_ its configuration.

But you could be right.. to allow `load-config` to just take a map and then run all the merges on that map might be useful in development / testing. When would you use it and how?

**Comment by lerouxrgd** [comment]
I am using `cprop` for configuring a `system` (from [component](https://github.com/stuartsierra/component) library).
All the config files are under a `config` directory and I intended to load them as follows:
```clj
(defn merge-configs [conf-from-app]
  (let [conf-from-sys (from-system-props)
        conf-from-env (from-env)
        env (name (or (:env conf-from-app) 
                      (:env conf-from-sys) 
                      (:env conf-from-env)
                      (throw (IllegalArgumentException. ":env is missing"))))]
    (load-config :merge [(from-file "config/defaults.edn")
                         conf-from-app
                         (from-file (str "config/" env ".edn"))
                         conf-from-sys
                         conf-from-env])))
```
That's how I got an error. 
Now I moved out `"config/defaults.edn"` into a `:file` parameter.

**Comment by tolitius** [comment]
It would all depend on how you choose to work with env overrides, but  there are options. The simplest way: you can have you `config.edn` living in the classpath / file system. You would start your application with something like `-Dconf=...` and export `ENV` variables to override env specific properties.

Besides exporting `ENV` variables manually / with a script, you can use something like [Consul](https://www.consul.io) or [etcd](https://coreos.com/etcd/) or [Zookeeper](https://zookeeper.apache.org/) to read those values.

Both solutions above would resolve in just:

```clojure
(load-config)
```

since cprop merges ENV variables by default.

Using a specific `conf.env` file for a specific environment is also of course an option. It can live in classpath / file system or could also live in consul/etc/zookeeper where, depending on env would be pushed to the app (or its docker image). In which case the you would just do:

```clojure
(load-config :merge [(from-file "conf.env")])
```

or `from-resource`, depending where this file is being placed.
