### ISSUE TITLE
handle non-existent (or empty) configurations

### ISSUE THREAD

**Issue by mbuczko** [tolitius/cprop#15]
This is actually not an issue but rather an ask for advice. I'd like to implement scenario where application could be configured by hierarchical (merged at the end) resources, eg:

app.edn
app-dev.edn
app-prod.edn

In this case app.config would contain all properties common for -dev and -prod environments. 

The problem is that for each environment I would like to have these files optional, eg. to have no app-dev.config for development environment (so only properties from app.edn would get loaded) or to not have app.edn at all (so only environment-specific resources would be loaded).

What I tried was something like this:

    (cprop/load-config :resource "app.edn"
                       :merge [(from-resource "app-dev.edn"))])

but it fails when any of resources does not exist or is empty. Is there any way to get my scenario working?

Thanks.

**Comment by tolitius** [comment]
## Default Overrides

If you have a `config.edn` in your classpath, `cprop` will read it first.

You can then supply a `-Dconf=/path/to/overrides.edn` as you are starting the app.

For example in `lein`:

```clojure
:profiles {:dev {;; ...
                 :jvm-opts ["-Dconf=dev-resources/dev-overrides.edn"]}
```

in `boot`:

```clojure
(deftask dev []
  (System/setProperty "conf" "dev-resources/dev-overrides.edn")
  ;; ...)
```

This way when you call `(load-config)` it will first read the classpath for "common" props, and then will merge `dev-overrides.edn` on top of it.

## ENV Overrides

Instead of `-D` you can also export `ENV` vars that would hierarchically match properties in the internal `config.edn`, and `(load-config)` will match them automatically, here is [more docs](https://github.com/tolitius/cprop#merging-with-env-variables) about it.

## Remote Overrides

You can also merge environment specific properties from Zookeep, etcd, Consul, etc.. For example [this Consul client](https://github.com/tolitius/envoy#merging-configurations) would take your config and would merge it with the values from Consul.

## The Idea

The idea is to keep you code (i.e. `(load-config.. )`) environment agnostic and manage different environments with overrides from that environment, whether it is `ENV`, Consul, `-D`, etc.

**Comment by mbuczko** [comment]
thanks for so detailed answer. is `config.edn` hardcoded as a name for "base" configuration or is it also configurable somehow?

**Comment by tolitius** [comment]
`config.edn` is hardcoded as the default, but can be overwritten with `:resource`:

```clojure
(load-config :resource "path/to/app.edn")
```

with all the above "overrides" strategies still apply.

**Comment by mbuczko** [comment]
great, that solves my problem :)
