### ISSUE TITLE
Different behavior of System/setProperty vs importing from env

### ISSUE THREAD

**Issue by WorldsEndless** [tolitius/cprop#16]
When in my repl use, 

(System/setProperty "FTTV_DB_classname" "value") I get what I want from cprop: 
`{:fttv {:db {:classname "value"}}}`

However, with the following in my bashrc, I have a problem:
`export FTTV_DB_CLASSNAME='org.postgresql.Driver'`

Results in {:fttv-db-classname "org.postgresql.Driver"}

What's going on?

**Comment by tolitius** [comment]
since `ENV` variables lack structure, use a double underscore to "get in" and a single underscore to "dash".

For example to override:

```clojure
{:fttv {:db {:classname "value"}}}
```

You could export `FTTV__DB__CLASSNAME=42` (notice the double underscore to "get in" to the nested value)

If you had a "dash" in your example, say:

```clojure
{:fttv {:db {:class-name "value"}}}
```

This would do it: `FTTV__DB__CLASS_NAME=42` (notice a single underscore to match class`-`name)

You can read more about it in a [Speaking ENV Variables](https://github.com/tolitius/cprop#speaking-env-variables) section in the docs

**Comment by WorldsEndless** [comment]
Excellent! Thanks. I had read that, but got confused by the different behavior when I used setProperty (which I considered to also be an env var). Thanks!
