### ISSUE TITLE
Merging a nil value nils the entire config

### ISSUE THREAD

**Issue by DarinDouglass** [tolitius/cprop#30]
If you pass a `nil` value when using the `:merge` keyword, the entire returned config is `nil`. 

```clojure
user> (require '[cprop.core :as cprop])
nil
user> (cprop/load-config)
{:hello :world, :foo "bar"}
user> (cprop/load-config :merge [nil])
nil
```
Given Clojure's handling of `nil`, the above result feels wrong. Below is a less contrived example:
```clojure
user> (require '[cprop.source :as source]
               '[clojure.java.io :as io])
nil
user> (defn optional-resource [path]
        (when (io/reader path)
          (source/from-resource path)))
nil
user> (cprop/load-config :merge [(optional-resource "maybe/a/missing/file.edn")])
nil
```
Possible solutions:

1) `(remove nil? merge)` [here](https://github.com/tolitius/cprop/blob/master/src/cprop/core.cljc#L22).
  This is a super simple change, however it doesn't alert the user that one of their resources isn't getting merged. This can lead to confusion if the config was expected to exist and be merged.
2) Allow [`ignore-missing-default`](https://github.com/tolitius/cprop/blob/master/src/cprop/source.cljc#L190) to return an empty map when providing a source.
  This could be a new arity or just a removal of the `(if source ...)` conditional. 
  ```clojure
  (def ignore-missing-default
    ([f source]
      (ignore-missing-default f source true))
    ([f source ignore-missing-source?]
      (try
       (f source)
       (catch MissingResourceException mre
         (when-not ignore-missing-source?
           (throw mre)
         (log/infof "Ignoring missing config: %s" source)
         {})
  ```

**Comment by tolitius** [comment]
thanks for reporting this and for the ideas, as these are the best kind of reports: ideas spark new ideas :)

it is not enough to attack this via your "idea 2", since someone can just do:
```clojure
(cprop/load-config :merge [nil])
```
which will bypass `ignore-missing-default`, but should also be handled.

as to your example with:
```clojure
(defn optional-resource [path]
  (when (io/reader path)
    (source/from-resource path)))

(cprop/load-config :merge [(optional-resource "maybe/a/missing/file.edn")])
```

cprop has I/O tools to use to pull in resources and files, and will throw in case the file or the resource does not exist:

```clojure
=> (require '[cprop.core :as c] '[cprop.source :as s] '[cprop.tools :as t])

=> (c/load-config :merge [(s/from-resource "does/not/exist")])

java.util.MissingResourceException: resource "does/not/exist" not found on the resource path
```
```clojure
=> (c/load-config :merge [(s/from-file "does/not/exist")])

java.util.MissingResourceException: can't find a configuration file path: "does/not/exist". besides providing it via "(load-config :file <path>)", it could also be set via "conf" system property (i.e. -Dconf=<path>)
```

so you can use them from `cprop.source`.

also in order to have a better visual on which file/resources were loaded, and which config values were overwritten you can use a `DEBUG` env, here is [an example](https://github.com/tolitius/cprop#see-which-files-were-loaded-and-what-properties-were-substituted).

---

given the above I like your first idea, but not in the top level namespace, but rather in tools where these maps get merged. this way, later, this tool maybe reused without suffering the same issue.

here is [the fix](https://github.com/tolitius/cprop/commit/a65b3ed308dcf007831f380978f9a545c2fd0b7a) and it is deployed as a part of [[0.1.15-SNAPSHOT]](https://clojars.org/cprop/versions/0.1.15-SNAPSHOT)

let me know if it works for you

**Comment by DarinDouglass** [comment]
I had forgotten about `DEBUG=y`. That should suffice for knowing if all files got merged properly. Works for me.

+1

**Comment by DarinDouglass** [comment]
I'll let you close this when `0.1.15` gets released?
